# Development Docker Compose for {{cookiecutter.project_name}}
version: '3.8'

services:
  # Database - conditional based on database_type
  {%- if cookiecutter.database_type == "postgresql" %}
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: {{cookiecutter.database_user}}
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: {{cookiecutter.database_name}}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{cookiecutter.database_user}}"]
      interval: 5s
      timeout: 5s
      retries: 5
  {%- elif cookiecutter.database_type == "mysql" %}
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: {{cookiecutter.database_name}}
      MYSQL_USER: {{cookiecutter.database_user}}
      MYSQL_PASSWORD: mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  {%- endif %}

  {%- if cookiecutter.include_redis == "y" %}
  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  {%- endif %}

  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      {%- if cookiecutter.database_type == "postgresql" %}
      - DATABASE_URL=postgresql://{{cookiecutter.database_user}}:postgres_password@postgres:5432/{{cookiecutter.database_name}}
      {%- elif cookiecutter.database_type == "mysql" %}
      - DATABASE_URL=mysql://{{cookiecutter.database_user}}:mysql_password@mysql:3306/{{cookiecutter.database_name}}
      {%- elif cookiecutter.database_type == "sqlite" %}
      - DATABASE_URL=sqlite:///./{{cookiecutter.database_name}}.db
      {%- endif %}
      {%- if cookiecutter.include_redis == "y" %}
      - REDIS_URL=redis://redis:6379/0
      {%- endif %}
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./alembic:/app/alembic
    depends_on:
      {%- if cookiecutter.database_type == "postgresql" %}
      postgres:
        condition: service_healthy
      {%- elif cookiecutter.database_type == "mysql" %}
      mysql:
        condition: service_healthy
      {%- endif %}
      {%- if cookiecutter.include_redis == "y" %}
      redis:
        condition: service_healthy
      {%- endif %}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  {%- if cookiecutter.database_type == "postgresql" %}
  postgres_data:
  {%- elif cookiecutter.database_type == "mysql" %}
  mysql_data:
  {%- endif %}
  {%- if cookiecutter.include_redis == "y" %}
  redis_data:
  {%- endif %}
